language: cpp

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode10.2
    compiler: clang

    script:
      - make
      - zip -qry -FS dmidecode-mac-$(cat version.h | cut -f2 -d'"').zip dmidecode

    deploy:
      provider: releases
      skip_cleanup: true
      file: "dmidecode-mac-*.zip"
      file_glob: true
      api_key:
        secure: sVfeHhQzewTsaIJLt474ZoCxU/gLWa0VKMpG3ndTKSrhvus+uqONcY9N9pat4e1/aWwtetjnNul+fYgyEeztoEn1tcCNoVYzo0eHlw7sCZ86yVJt6LVILnb1JKbbkB1FJFPR7UcNW3Jq3h3B1+Il0447Np/8tMWeaQ/1SbRru9/HcPYhR+NASMzAvHzT3kJ8lJZEbevosyGo3xFdA3JjI5zh0dMBr+qKd514TRI51JjQ8ia1RCGuQdQ2CgguiOg59lvkiBCZgBiE/CYpSY4rEaGp/FZlZCrhTT18CyFOeJMOUaBrGqcnPGqdA3yusA4N4/0BoQRjrLsCuKlGJCAeOGuq47TBnJNwpKCYqM24tnU+TsXIKqHIb/VkH9m45HgMXOIjt9/yMQDdBScP4RcD3QyLtDaO40s3+YqlQrdeJ+KRAnhiKf7ONYyZ5gmkW4IyLbtB/GsADW7gIYheWpHFNy9bLU3XOOZMZiGB6AquHrrbMe1WCZ3RYU93ilqNRNVcaemKQ88ru/M6qWSYRfR0n+hSFRfwF7j/0kZn0QBhIpAm8rX+ixGg623xbqqNEyq106V3Pa5gRt9khDn2xWRdMeLFpN1rKWwZsbEKTSxTHJduFXjx8PAhRN9IlbtRHLvr8H8KPXRxcFHR8n1yNL2zXnTeVVyB0q63lD/bl8/7N+s=
      on:
        tags: true
